---
kind: pipeline
name: checks

trigger:
  event:
    - tag
    - push

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG:-develop}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - ${DRONE_TAG:-develop}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - tag
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG:-develop}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - ${DRONE_TAG:-develop}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG:-develop}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - ${DRONE_TAG:-develop}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: manifest

trigger:
  event:
    - tag
    - push

steps:
- name: manifest
  image: plugins/manifest
  pull: always
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl

depends_on:
  - linux-amd64
  - linux-arm64
  - linux-arm
