---
kind: pipeline
name: checks

trigger:
  event:
    - tag
    - push

steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine
  pull: always
  commands:
    - shellcheck --version
    - for file in $(find ./root -type f); do echo $file; shellcheck $file; done;

---
kind: pipeline
name: develop-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli:develop
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - develop-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: develop-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli:develop
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - develop-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: develop-arm

platform:
  os: linux
  arch: arm

trigger:
  event:
    - push

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli:develop
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - develop-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: release-amd64

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - tag

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - ${DRONE_TAG}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: release-arm64

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - tag

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - ${DRONE_TAG}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: release-arm

platform:
  os: linux
  arch: arm

trigger:
  event:
    - tag

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: hotio/tautulli
    cache_from: hotio/tautulli
    build_args:
      - GIT_COMMIT=${DRONE_COMMIT_SHA}
      - GIT_TAG=${DRONE_TAG}
      - ARCH=${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}
    tags:
      - ${DRONE_TAG}-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}

depends_on:
  - checks

---
kind: pipeline
name: manifest

trigger:
  event:
    - tag
    - push

steps:
- name: manifest
  image: plugins/manifest
  pull: always
  settings:
    ignore_missing: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: manifest.tmpl

depends_on:
  - develop-amd64
  - develop-arm64
  - develop-arm
  - release-amd64
  - release-arm64
  - release-arm
