---
kind: pipeline
name: dockerhub-description

trigger:
  event:
    - push
  branch:
    - master

steps:
- name: update
  image: peterevans/dockerhub-description:2.0.0
  pull: always
  environment:
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPOSITORY: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME##docker-}
